# basic
# ============================================================================
# if your site is serving on https://xxx.github.io, set `baseurl: /`
# if your site is serving on https://xxx.github.io/path, set `baseurl: /path`
baseurl: /

# site title
title: Starla House

# default variables for post-type page
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      comment: true


# sass
# ============================================================================
sass:
  sass_dir: _sass
  style: compressed


# exclude none site related files
# ============================================================================
exclude:
  - README.md
  - LICENSE
  - github
  - package.json
  - package-lock.json
  - node_modules
